/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHeader {
    'isLogin': boolean;
    'title': string;
  }
  interface AppRoot {}
  interface GoogleMap {}
  interface PageLogin {}
  interface PageTabs {}
  interface TabHome {}
  interface TabMap {}
}

declare global {


  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLGoogleMapElement extends Components.GoogleMap, HTMLStencilElement {}
  var HTMLGoogleMapElement: {
    prototype: HTMLGoogleMapElement;
    new (): HTMLGoogleMapElement;
  };

  interface HTMLPageLoginElement extends Components.PageLogin, HTMLStencilElement {}
  var HTMLPageLoginElement: {
    prototype: HTMLPageLoginElement;
    new (): HTMLPageLoginElement;
  };

  interface HTMLPageTabsElement extends Components.PageTabs, HTMLStencilElement {}
  var HTMLPageTabsElement: {
    prototype: HTMLPageTabsElement;
    new (): HTMLPageTabsElement;
  };

  interface HTMLTabHomeElement extends Components.TabHome, HTMLStencilElement {}
  var HTMLTabHomeElement: {
    prototype: HTMLTabHomeElement;
    new (): HTMLTabHomeElement;
  };

  interface HTMLTabMapElement extends Components.TabMap, HTMLStencilElement {}
  var HTMLTabMapElement: {
    prototype: HTMLTabMapElement;
    new (): HTMLTabMapElement;
  };
  interface HTMLElementTagNameMap {
    'app-header': HTMLAppHeaderElement;
    'app-root': HTMLAppRootElement;
    'google-map': HTMLGoogleMapElement;
    'page-login': HTMLPageLoginElement;
    'page-tabs': HTMLPageTabsElement;
    'tab-home': HTMLTabHomeElement;
    'tab-map': HTMLTabMapElement;
  }
}

declare namespace LocalJSX {
  interface AppHeader extends JSXBase.HTMLAttributes<HTMLAppHeaderElement> {
    'isLogin'?: boolean;
    'title'?: string;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface GoogleMap extends JSXBase.HTMLAttributes<HTMLGoogleMapElement> {}
  interface PageLogin extends JSXBase.HTMLAttributes<HTMLPageLoginElement> {}
  interface PageTabs extends JSXBase.HTMLAttributes<HTMLPageTabsElement> {}
  interface TabHome extends JSXBase.HTMLAttributes<HTMLTabHomeElement> {}
  interface TabMap extends JSXBase.HTMLAttributes<HTMLTabMapElement> {}

  interface IntrinsicElements {
    'app-header': AppHeader;
    'app-root': AppRoot;
    'google-map': GoogleMap;
    'page-login': PageLogin;
    'page-tabs': PageTabs;
    'tab-home': TabHome;
    'tab-map': TabMap;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


